root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  getting-started: getting-started/what-is-imp-money.md
  referrals: referrals/overview.md
  leadership: leadership/8-rank-system.md
  contracts: contracts/addresses.md
  faq: faq/general.md
